sudo: required
language: go

go:
  - 1.12.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - mkdir -p $TRAVIS_BUILD_DIR/build/_output/bin
  - curl -Lo $TRAVIS_BUILD_DIR/build/_output/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.8.1/operator-sdk-v0.8.1-x86_64-linux-gnu && chmod +x $TRAVIS_BUILD_DIR/build/_output/bin/operator-sdk

script:
  - make build

after_success:
  - if [ ! -s "$TRAVIS_TAG" ] ; then
      docker tag sinoreps/cmpp-operator:latest sinoreps/cmpp-operator:$TRAVIS_TAG;
      echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
      docker push sinoreps/cmpp-operator:$TRAVIS_TAG;

      docker tag sinoreps/cmpp-operator:latest quay.io/sinoreps/cmpp-operator:$TRAVIS_TAG;
      echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
      docker push quay.io/sinoreps/cmpp-operator:$TRAVIS_TAG;
    fi